### ISSUE TITLE
[Bug] -P2: could not create a new site when there is no site record  created before.

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#299] opened 2015-02-11 17:40 UTC
Client ID: unknow, the estimate time 1Hr, the deadline March 05, 2015.
Have multiple site enabled.
There was no site created before. Go to admin, click on Satellite Site, try to create a new site. Failed.

**Comment by zhoulingmin** [comment] 2015-03-04 04:16
@annie-zhou   I have enabled multsites, but couldn't reproduce this bug.

**Comment by annie-zhou** [comment] 2015-03-04 15:04
Does your db have data saved before for mutliple site ? We could reproduce
it if it's freshly built db.

On Tue, Mar 3, 2015 at 11:16 PM, zhoulingmin <notifications@github.com>
wrote:

> @annie-zhou <https://github.com/annie-zhou> I have enabled multsites, but
> couldn't reproduce this bug.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/oscaremr/oscar/issues/299#issuecomment-77094513>.
>



-- 
NOTICE: All information in and attached to the e-mails below may be
proprietary, confidential, privileged and otherwise protected from improper
or erroneous disclosure. If you are not the sender's intended recipient,
you are not authorized to intercept, read, print, retain, copy, forward, or
disseminate this message. If you have erroneously received this
communication, please notify the sender immediately by phone (1-855-696-7227
<%28704-758-1000>) or by e-mail and destroy all copies of this message
electronic, paper, or otherwise.

*By transmitting documents via this email: Users, Customers, Suppliers and
Vendors collectively acknowledge and agree the transmittal of information
via email is voluntary, is offered as a convenience, and is not a secured
method of communication; Not to transmit any payment information E.G.
credit card, debit card, checking account, wire transfer information,
passwords, or sensitive and personal information E.G. Driver's license,
DOB, social security, or any other information the user wishes to remain
confidential; To transmit only non-confidential information such as plans,
pictures and drawings and to assume all risk and liability for and
indemnify OSCAR Service from any claims, losses or damages that may arise
from the transmittal of documents or including non-confidential information
in the body of an email transmittal. Thank you.*

**Comment by zhoulingmin** [comment] 2015-03-05 04:01
I created a new database by use of createdatabase_on.sh, but couldn't reproduce it.
Can you give me the exception stack?

**Comment by annie-zhou** [comment] 2015-03-05 18:36
That's weird. Now I could not reproduce either...But Toby and I once saw it
clearly happened when we tried to set up multiple site for one
clinic...anyway, I am going to close this bug. Once it happens again, I
will reopen it.

Annie

On Wed, Mar 4, 2015 at 11:02 PM, zhoulingmin <notifications@github.com>
wrote:

> I created a new database by use of createdatabase_on.sh, but couldn't
> reproduce it.
> Can you give me the exception stack?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/oscaremr/oscar/issues/299#issuecomment-77302740>.
>



-- 
NOTICE: All information in and attached to the e-mails below may be
proprietary, confidential, privileged and otherwise protected from improper
or erroneous disclosure. If you are not the sender's intended recipient,
you are not authorized to intercept, read, print, retain, copy, forward, or
disseminate this message. If you have erroneously received this
communication, please notify the sender immediately by phone (1-855-696-7227
<%28704-758-1000>) or by e-mail and destroy all copies of this message
electronic, paper, or otherwise.

*By transmitting documents via this email: Users, Customers, Suppliers and
Vendors collectively acknowledge and agree the transmittal of information
via email is voluntary, is offered as a convenience, and is not a secured
method of communication; Not to transmit any payment information E.G.
credit card, debit card, checking account, wire transfer information,
passwords, or sensitive and personal information E.G. Driver's license,
DOB, social security, or any other information the user wishes to remain
confidential; To transmit only non-confidential information such as plans,
pictures and drawings and to assume all risk and liability for and
indemnify OSCAR Service from any claims, losses or damages that may arise
from the transmittal of documents or including non-confidential information
in the body of an email transmittal. Thank you.*

**Closed** 2015-03-05 18:36 UTC
Labels: bug
